name: water-demand-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - numpy=1.24.3
  - plotly=5.17.0
  - flask-cors=4.0.0
